require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks!
target 'DoneWithIt' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNPdfScanner', :path => '../node_modules/react-native-document-scanner'

  pod 'RNRectangleScanner', :path => '../node_modules/react-native-rectangle-scanner'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNFS', :path => '../node_modules/react-native-fs'


  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  target 'DoneWithItTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'DoneWithIt-tvOS' do
  # Pods for DoneWithIt-tvOS

  target 'DoneWithIt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
